name: Flake ❄️ Checker ✅

on:
  push:
    branches:
      - main
  schedule:
    # l33t o'clock
    - cron: '37 13 * * *'
  workflow_dispatch:

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: DeterminateSystems/flake-checker-action@v5
